#!/bin/bash

source ./service.env



docker-compose down "$@"

docker-compose run --rm django_service bash -ci "\
    cd /home/ && \
	chown -R `stat -c %g .`.`stat -c %u .` ./service && \
	cd /home/appserver/media && \
	chown -R `stat -c %g .`.`stat -c %u .` ./cmsdb && \
	chmod -R 777 ./cmsdb" \
&& echo "Done."