# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailimages', '0016_deprecate_rendition_filter_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialActionButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.CharField(blank=True, choices=[('', 'Default'), ('small', 'Small'), ('big', 'Big')], default='', max_length=25)),
                ('icon', models.CharField(max_length=25)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='EditorialActionButtonPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('action_button', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.EditorialActionButton')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='EditorialFeatureArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('feature_article_heading', models.CharField(blank=True, default='', max_length=255)),
                ('feature_text', wagtail.wagtailcore.fields.RichTextField(blank='True')),
                ('feature_icon', models.CharField(blank='True', default='', max_length=25)),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='EditorialPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('header_title', models.CharField(max_length=255, verbose_name='Heading')),
                ('header_subtitle', models.CharField(blank=True, default='', max_length=255, verbose_name='Subtitle')),
                ('banner_display', models.BooleanField(default=True)),
                ('banner_heading', models.CharField(blank=True, default='', max_length=255)),
                ('banner_heading_line2', models.CharField(blank='True', default='', max_length=255, verbose_name='Headling, 2nd line')),
                ('banner_abstract', models.CharField(blank='True', default='', max_length=4096)),
                ('banner_text', wagtail.wagtailcore.fields.RichTextField(blank='True')),
                ('feature_display', models.BooleanField(default=True)),
                ('feature_heading', models.CharField(blank=True, default='', max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('date', models.DateField(verbose_name='Post date')),
                ('banner_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EditorialSocialMediaLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(choices=[('fa-linkedin', 'fa-linkedin'), ('fa-facebook', 'fa-facebook'), ('fa-twitter', 'fa-twitter'), ('fa-instagram', 'fa-instagram'), ('fa-medium', 'fa-medium')], default='linkedin', max_length=25)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Social Media Links',
                'verbose_name': 'Social Media Link',
            },
        ),
        migrations.CreateModel(
            name='EditorialSocialMediaLinkPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_link_placements', to='home.EditorialPage')),
                ('social_media_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.EditorialSocialMediaLink')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='editorialfeaturearticle',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_articles', to='home.EditorialPage'),
        ),
        migrations.AddField(
            model_name='editorialactionbuttonplacement',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_button_placements', to='home.EditorialPage'),
        ),
    ]
