# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('author', models.CharField(max_length=255)),
                ('date', models.DateField(verbose_name='Post date')),
                ('main', wagtail.wagtailcore.fields.StreamField((('tile', wagtail.wagtailcore.blocks.StructBlock((('style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('style1', 'Style1'), ('style2', 'Style2'), ('style3', 'Style3'), ('style4', 'Style4'), ('style5', 'Style5')])), ('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('content', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=True)), ('url', wagtail.wagtailcore.blocks.URLBlock())))),))),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
