# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0016_deprecate_rendition_filter_relation'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialActionButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.CharField(choices=[('', 'Default'), ('small', 'Small'), ('big', 'Big')], default='', max_length=25)),
                ('icon', models.CharField(max_length=25)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='EditorialActionButtonPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('action_button', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.EditorialActionButton')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='editorialpage',
            old_name='headersubtitle',
            new_name='header_subtitle',
        ),
        migrations.RenameField(
            model_name='editorialpage',
            old_name='headertitle',
            new_name='header_title',
        ),
        migrations.AddField(
            model_name='editorialpage',
            name='banner_abstract',
            field=models.CharField(blank='True', default='', max_length=4096),
        ),
        migrations.AddField(
            model_name='editorialpage',
            name='banner_heading',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='editorialpage',
            name='banner_heading_line2',
            field=models.CharField(blank='True', default='', max_length=255, verbose_name='Headling, 2nd line'),
        ),
        migrations.AddField(
            model_name='editorialpage',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='editorialpage',
            name='banner_text',
            field=wagtail.wagtailcore.fields.RichTextField(blank='True'),
        ),
        migrations.AddField(
            model_name='editorialactionbuttonplacement',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_button_placements', to='home.EditorialPage'),
        ),
    ]
