# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorialactionbutton',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='editorialpage',
            name='banner_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='editorialpage',
            name='feature_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='editorialpage',
            name='post_display',
            field=models.BooleanField(default=False),
        ),
    ]
