# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorialsocialmedialinkplacement',
            name='social_media_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_media_link_placement', to='home.EditorialSocialMediaLink'),
        ),
    ]
