# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170218_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorialpage',
            name='generic_headling',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
