# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170108_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorialpage',
            name='banner_display',
            field=models.BooleanField(default=True),
        ),
    ]
