# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_socialmedialink'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedialink',
            name='icon',
            field=models.CharField(choices=[('LinkedIn', 'linkedin'), ('Facebook', 'facebook'), ('Twitter', 'twitter')], default='Twitter', max_length=25),
        ),
    ]
