# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_socialmedialink_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialink',
            name='icon',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('twitter', 'Twitter')], default='Twitter', max_length=25),
        ),
    ]
