# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_editorialpage_generic_headling'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editorialpage',
            old_name='generic_headling',
            new_name='generic_headline',
        ),
    ]
