# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170122_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorialactionbutton',
            name='size',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('small', 'Small'), ('big', 'Big')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='editorialactionbutton',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
