# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 14:52
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170103_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='section_stream',
            field=wagtail.wagtailcore.fields.StreamField((('banner', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('headingline2', wagtail.wagtailcore.blocks.CharBlock()), ('headingtext', wagtail.wagtailcore.blocks.CharBlock()), ('content', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=True))))), ('features', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('features', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(default='')), ('content', wagtail.wagtailcore.blocks.RichTextBlock()), ('icon', wagtail.wagtailcore.blocks.CharBlock(default='', verbose_name='Icon'))))))))))),
        ),
    ]
