# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170122_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorialactionbutton',
            name='url',
        ),
        migrations.AlterField(
            model_name='editorialactionbutton',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
