# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170110_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorialactionbutton',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
