# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20161211_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedialink',
            options={},
        ),
        migrations.RemoveField(
            model_name='socialmedialink',
            name='page',
        ),
        migrations.RemoveField(
            model_name='socialmedialink',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='main',
            field=wagtail.wagtailcore.fields.StreamField(()),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='icon',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('medium', 'Medium')], default='linkedin', max_length=25),
        ),
    ]
