# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170110_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialPostArticleActionButtonPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='EditorialActionButton',
            new_name='ActionButton',
        ),
        migrations.RemoveField(
            model_name='editorialactionbuttonplacement',
            name='action_button',
        ),
        migrations.RemoveField(
            model_name='editorialactionbuttonplacement',
            name='page',
        ),
        migrations.AddField(
            model_name='editorialpostarticle',
            name='button',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.ActionButton'),
        ),
        migrations.DeleteModel(
            name='EditorialActionButtonPlacement',
        ),
        migrations.AddField(
            model_name='editorialpostarticleactionbuttonplacement',
            name='action_button',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.ActionButton'),
        ),
        migrations.AddField(
            model_name='editorialpostarticleactionbuttonplacement',
            name='parent',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='home.EditorialPostArticle'),
        ),
    ]
