# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170110_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorialpostarticle',
            name='button',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.EditorialActionButton'),
        ),
    ]
