# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170122_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorialactionbutton',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
