# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_editorialactionbutton_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionButtonPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_button', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.EditorialActionButton')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_button_placements', to='home.EditorialPostArticle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='editorialactionbuttonplacement',
            name='action_button',
        ),
        migrations.RemoveField(
            model_name='editorialactionbuttonplacement',
            name='id',
        ),
        migrations.AddField(
            model_name='editorialactionbuttonplacement',
            name='actionbuttonplacement_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.ActionButtonPlacement'),
            preserve_default=False,
        ),
    ]
