# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20161211_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialink',
            name='icon',
            field=models.CharField(choices=[('linkedin', 'fa-linkedin'), ('facebook', 'fa-facebook'), ('twitter', 'fa-twitter'), ('instagram', 'fa-instagram'), ('medium', 'fa-medium')], default='linkedin', max_length=25),
        ),
    ]
