# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20161211_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialink',
            name='icon',
            field=models.CharField(choices=[('fa-linkedin', 'fa-linkedin'), ('fa-facebook', 'fa-facebook'), ('fa-twitter', 'fa-twitter'), ('fa-instagram', 'fa-instagram'), ('fa-medium', 'fa-medium')], default='linkedin', max_length=25),
        ),
    ]
