# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_socialmedialinkplacement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedialink',
            options={'verbose_name': 'Social Media Link', 'verbose_name_plural': 'Social Media Links'},
        ),
        migrations.AlterModelOptions(
            name='socialmedialinkplacement',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='homepage',
            name='headersubtitle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='headertitle',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
