# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20161212_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialinkplacement',
            name='social_media_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.SocialMediaLink'),
        ),
    ]
