# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 23:06
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20161212_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='main',
        ),
        migrations.AddField(
            model_name='homepage',
            name='sectionstream',
            field=wagtail.wagtailcore.fields.StreamField((('banner', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('headingline2', wagtail.wagtailcore.blocks.CharBlock()), ('headingtext', wagtail.wagtailcore.blocks.CharBlock()), ('content', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=True))))),), default=None),
            preserve_default=False,
        ),
    ]
