# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpage_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='blog_heading',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
