# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogindexpage_blog_heading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogindexpage',
            old_name='blog_heading',
            new_name='heading',
        ),
    ]
